services:
  backend:
    build:
      context: ./apps/backend/
      dockerfile: Dockerfile
    container_name: db-manager-server
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    restart: unless-stopped